/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Citas;

import Services.Add;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Yanir
 */
public class Historia extends javax.swing.JPanel {

    /**
     * Creates new form Historia
     */
    private String id = "1";
    public Historia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PacienteLbl = new javax.swing.JLabel();
        MotivoLbl = new javax.swing.JLabel();
        HistoriaLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoriaTxtArea = new javax.swing.JTextArea();
        AceptarBtn = new javax.swing.JButton();
        SalirBtn = new javax.swing.JButton();
        TratamientoLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TratamientoTxtArea = new javax.swing.JTextArea();
        FechaLbl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Historia"));

        PacienteLbl.setText("Paciente:");

        MotivoLbl.setText("Motivo:");

        HistoriaLbl.setText("Historia:");

        HistoriaTxtArea.setColumns(20);
        HistoriaTxtArea.setRows(5);
        jScrollPane1.setViewportView(HistoriaTxtArea);

        AceptarBtn.setText("Aceptar");
        AceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtnActionPerformed(evt);
            }
        });

        SalirBtn.setText("Atrás");

        TratamientoLbl.setText("Tratamiento:");

        TratamientoTxtArea.setColumns(20);
        TratamientoTxtArea.setRows(5);
        jScrollPane2.setViewportView(TratamientoTxtArea);

        FechaLbl.setText("Fecha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SalirBtn)
                        .addGap(18, 18, 18)
                        .addComponent(AceptarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PacienteLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(MotivoLbl)
                        .addGap(138, 138, 138)
                        .addComponent(FechaLbl)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TratamientoLbl)
                            .addComponent(HistoriaLbl))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PacienteLbl)
                    .addComponent(MotivoLbl)
                    .addComponent(FechaLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HistoriaLbl)
                        .addGap(0, 181, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TratamientoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AceptarBtn)
                    .addComponent(SalirBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtnActionPerformed
        try {
            
            JSONObject historia_paciente=new JSONObject();
            historia_paciente.put("id","1");
            historia_paciente.put("tratamiento",TratamientoTxtArea.getText());
            historia_paciente.put("diagnostico",HistoriaTxtArea.getText());
            new Add().add("http://localhost/API_Citas/public/Citas/edit/" + this.id, historia_paciente);   
        
        } catch (JSONException | IOException ex) {
            Logger.getLogger(Historia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AceptarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBtn;
    private javax.swing.JLabel FechaLbl;
    private javax.swing.JLabel HistoriaLbl;
    private javax.swing.JTextArea HistoriaTxtArea;
    private javax.swing.JLabel MotivoLbl;
    private javax.swing.JLabel PacienteLbl;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JLabel TratamientoLbl;
    private javax.swing.JTextArea TratamientoTxtArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
