/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Citas;

import Services.Add;
import Services.Leer;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Yanir
 */


public class Usuario extends javax.swing.JFrame {
    
    Leer rutasLeer;
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        
        initComponents();
        StatusMedico();
        rutasLeer = new Leer();
        try {
            JSONArray Asistentes = new JSONArray();
            Asistentes = rutasLeer.leer("http://localhost/API_Citas/public/Asistentes/all");
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0;i<Asistentes.length();i++){
                
                JSONObject obj = (JSONObject)Asistentes.get(i);
                System.out.println("ENTRE EN EL FOR " + i + ": "+ obj.toString());
                modelo.addElement(obj.getString("identificacion"));
            }
            
            AsistentesList.setModel(modelo);
            
        } catch (IOException | JSONException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AceptarBtn = new javax.swing.JButton();
        EditarBtn = new javax.swing.JButton();
        SalirBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MedicoChckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        EspecialidadTxtF = new javax.swing.JTextField();
        CompartirChckBox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        AtencionSpin = new javax.swing.JSpinner();
        MinutosLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Lunes = new javax.swing.JCheckBox();
        Martes = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        Miercoles = new javax.swing.JCheckBox();
        Jueves = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        AsistentesList = new javax.swing.JList<>();
        Viernes = new javax.swing.JCheckBox();
        Sabado = new javax.swing.JCheckBox();
        Domingo = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        HorarioTxtF1 = new javax.swing.JTextField();
        HorarioTxtF2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ApellidoTxtF = new javax.swing.JTextField();
        UsuarioTxtF = new javax.swing.JTextField();
        PassTxtF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        IdentificacionTxtF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TelefonoTxtF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CorreoTxtF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NombreTxtF = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AceptarBtn.setText("Aceptar");
        AceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtnActionPerformed(evt);
            }
        });

        EditarBtn.setText("Editar");

        SalirBtn.setText("Salir");
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del médico"));

        MedicoChckBox.setText("Médico");
        MedicoChckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicoChckBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Especialidad:");

        CompartirChckBox.setText("Compartir información del paciente");

        jLabel9.setText("Tiempo de atención:");

        MinutosLbl.setText("Minutos");

        jLabel11.setText("Días de atención:");

        Lunes.setText("L");

        Martes.setText("M");

        jLabel10.setText("Asistente:");

        Miercoles.setText("M");

        Jueves.setText("J");

        jScrollPane1.setViewportView(AsistentesList);

        Viernes.setText("V");

        Sabado.setText("S");

        Domingo.setText("D");

        jLabel12.setText("Horario de atención:");

        HorarioTxtF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorarioTxtF1ActionPerformed(evt);
            }
        });

        jLabel13.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedicoChckBox)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EspecialidadTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Lunes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Martes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Miercoles)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Jueves)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Viernes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Sabado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Domingo))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(AtencionSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MinutosLbl))
                                    .addComponent(CompartirChckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(HorarioTxtF1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HorarioTxtF2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MedicoChckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EspecialidadTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CompartirChckBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AtencionSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinutosLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Lunes)
                    .addComponent(Martes)
                    .addComponent(Miercoles)
                    .addComponent(Jueves)
                    .addComponent(Viernes)
                    .addComponent(Sabado)
                    .addComponent(Domingo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(HorarioTxtF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HorarioTxtF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("Identificación:");

        jLabel6.setText("Teléfono:");

        jLabel7.setText("Correo:");

        NombreTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ApellidoTxtF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(UsuarioTxtF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PassTxtF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdentificacionTxtF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefonoTxtF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorreoTxtF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreTxtF)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ApellidoTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UsuarioTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PassTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IdentificacionTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TelefonoTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CorreoTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SalirBtn)
                        .addGap(18, 18, 18)
                        .addComponent(EditarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(AceptarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirBtn)
                    .addComponent(EditarBtn)
                    .addComponent(AceptarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtFActionPerformed

    private void AceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtnActionPerformed
        if(!NombreTxtF.equals("")){
            if(!ApellidoTxtF.equals("")){
                if(!UsuarioTxtF.equals("")){
                    if(!PassTxtF.equals("")){
                        if(!IdentificacionTxtF.equals("")){
                            
                            try {
                                //Usuario
                                JSONObject Usuario=new JSONObject();
                                Usuario.put("identificacion",IdentificacionTxtF.getText());
                                Usuario.put("username",UsuarioTxtF.getText());
                                Usuario.put("password",PassTxtF.getText());
                                Usuario.put("name",NombreTxtF.getText());
                                Usuario.put("last_name",ApellidoTxtF.getText());
                                Usuario.put("tlf",TelefonoTxtF.getText());
                                Usuario.put("email", CorreoTxtF.getText());
                                
                                if(MedicoChckBox.isSelected()){
                                    Usuario.put("especialidad", EspecialidadTxtF.getText());
                                    Usuario.put("comparte", CompartirChckBox.isSelected());
                                    Usuario.put("tiempoatencion", AtencionSpin.getValue());
                                    Usuario.put("lunes",Lunes.isSelected());
                                    Usuario.put("martes",Martes.isSelected());
                                    Usuario.put("miercoles",Miercoles.isSelected());
                                    Usuario.put("jueves",Jueves.isSelected());
                                    Usuario.put("viernes",Viernes.isSelected());
                                    Usuario.put("sabado",Sabado.isSelected());
                                    Usuario.put("domingo",Domingo.isSelected());
                                    Usuario.put("asistente", AsistentesList.getSelectedValue());
                                    Usuario.put("horainicio", HorarioTxtF1.getText() );
                                    Usuario.put("horafin", HorarioTxtF2.getText());
                                    Usuario.put("medico", MedicoChckBox.isSelected());
                                }
                                
                                new Add().add("http://localhost/API_Citas/public/create", Usuario);
                                System.out.println(Usuario);
                            } catch (JSONException | IOException ex) {
                                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "El campo 'Identificación' no puede estar vacío."  ,"Alerta.", JOptionPane.WARNING_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "El campo 'Contraseña' no puede estar vacío."  ,"Alerta.", JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El campo 'Usuario' no puede estar vacío."  ,"Alerta.", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "El campo 'Apellido' no puede estar vacío."  ,"Alerta.", JOptionPane.WARNING_MESSAGE);
            }
        }else{
             JOptionPane.showMessageDialog(null, "El campo 'Nombre' no puede estar vacío."  ,"Alerta.", JOptionPane.WARNING_MESSAGE);
        }
        
        dispose();
    }//GEN-LAST:event_AceptarBtnActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        dispose();
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void MedicoChckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicoChckBoxActionPerformed
        StatusMedico();
    }//GEN-LAST:event_MedicoChckBoxActionPerformed

    private void HorarioTxtF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorarioTxtF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorarioTxtF1ActionPerformed

    
    public void StatusMedico(){
        if(MedicoChckBox.isSelected()){
            EspecialidadTxtF.setEnabled(true);
            CompartirChckBox.setEnabled(true);
            AtencionSpin.setEnabled(true);
            MinutosLbl.setEnabled(true);
            Lunes.setEnabled(true);
            Martes.setEnabled(true);
            Miercoles.setEnabled(true);
            Jueves.setEnabled(true);
            Viernes.setEnabled(true);
            Sabado.setEnabled(true);
            Domingo.setEnabled(true);
        }else{
            EspecialidadTxtF.setEnabled(false);
            CompartirChckBox.setEnabled(false);
            AtencionSpin.setEnabled(false);
            MinutosLbl.setEnabled(false);
            Lunes.setEnabled(false);
            Martes.setEnabled(false);
            Miercoles.setEnabled(false);
            Jueves.setEnabled(false);
            Viernes.setEnabled(false);
            Sabado.setEnabled(false);
            Domingo.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBtn;
    private javax.swing.JTextField ApellidoTxtF;
    private javax.swing.JList<String> AsistentesList;
    private javax.swing.JSpinner AtencionSpin;
    private javax.swing.JCheckBox CompartirChckBox;
    private javax.swing.JTextField CorreoTxtF;
    private javax.swing.JCheckBox Domingo;
    private javax.swing.JButton EditarBtn;
    private javax.swing.JTextField EspecialidadTxtF;
    private javax.swing.JTextField HorarioTxtF1;
    private javax.swing.JTextField HorarioTxtF2;
    private javax.swing.JTextField IdentificacionTxtF;
    private javax.swing.JCheckBox Jueves;
    private javax.swing.JCheckBox Lunes;
    private javax.swing.JCheckBox Martes;
    private javax.swing.JCheckBox MedicoChckBox;
    private javax.swing.JCheckBox Miercoles;
    private javax.swing.JLabel MinutosLbl;
    private javax.swing.JTextField NombreTxtF;
    private javax.swing.JTextField PassTxtF;
    private javax.swing.JCheckBox Sabado;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JTextField TelefonoTxtF;
    private javax.swing.JTextField UsuarioTxtF;
    private javax.swing.JCheckBox Viernes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
